### ISSUE TITLE
Failures in handlers are not catched

### ISSUE THREAD

**Issue by r7kamura** [r7kamura/serverkit#15]
``` yml
resources:
  - type: remote_file
    destination: /etc/nginx/nginx.conf
    group: root
    mode: 0644
    owner: root
    source: serverkit/nginx.conf
    notify:
      - restart_nginx
handlers:
  - id: restart_nginx
    type: command
    script: nginx -s reload
```

```
Running nginx -s reload on example
nginx: [emerg] invalid number of arguments in "ssl_dhparam" directive in /etc/nginx/nginx.conf:47
Finished with 1 on example
[DONE] command restart_nginx on example
```
